name: todo_app
description: A simple todo app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  provider: ^6.0.2
  rxdart: ^0.27.4
  persian_datetime_picker: ^2.5.0
  persian_number_utility: ^1.1.2
  flutter_local_notifications: ^9.7.0
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  test: ^1.21.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/pic1.jpg
    - assets/sounds/
  fonts:
    - family: Dirooz
      fonts:
        - asset: assets/Dirooz.ttf
